services:
  postgres:
    image: postgres:16
    container_name: dwarves-db
    environment:
      POSTGRES_DB: dwarves
      POSTGRES_USER: survey_user
      POSTGRES_PASSWORD: survey_pass
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: